"""tetranomicon の素材名(tetra.material.*)を生成 → tr/batch_18_tetranomicon_gen.json

「X socket」は「Xのソケット」、「§6X§r」のような色付き接頭辞は色コードを残して訳す。
"""
import json, re
from pathlib import Path

WORK = Path(__file__).parent
D = dict(l.split("=", 1) for l in """
Abyssmarine=アビスマリン
Acai Vine=アサイーのツタ
Adamantine=アダマンティン
Adamantite=アダマンタイト
Aeronos=エアロノス
Aeternium=エテルニウム
Alexandrite=アレキサンドライト
Allurite Shard=アルライトの欠片
Alpha Oak=アルファオーク
Aluminium=アルミニウム
Amber Chunk=琥珀の塊
Amber Curiosity=琥珀の珍品
Amethyst=アメジスト
Amethyst Steel=アメジスト鋼
Ammolite=アンモライト
Anchor Wood=アンカーウッド
Antarctopelta Plate=アンタークトペルタの装甲板
Aquamarine=アクアマリン
Aquatic Dragon Scale=水竜の鱗
Aquiris Ember=アクイリスの燃えさし
Aquiris Ember Rod=アクイリスの燃えさしの棒
Arcane Crystal=秘術の結晶
Archaic Vine=古代のツタ
Argillite=泥岩
Ashen=灰色の
Aspen=ポプラ
Astral=星界の
Astral Crystal=星界の結晶
Auric=金色の
Aurora Crystal=オーロラの結晶
Aurum=アウルム
Azure Jadestone=紺碧の翡翠石
Azure Silver Nugget=アズールシルバーの塊
Azure Vine=紺碧のツタ
Azure Vines=紺碧のツタ
Azure Wood=紺碧の木
Azurite=アズライト
Azurite Gem=アズライトの宝石
Bamboo Stick=竹の棒
Baobab=バオバブ
Beige Limestone=ベージュの石灰岩
Black Diamond=黒ダイヤモンド
Black Opal=ブラックオパール
Black Vine=黒いツタ
Blackwood=ブラックウッド
Blooming Vine=花咲くツタ
Blue Bioshroom=青色のバイオシュルーム
Blue Obsidian=青い黒曜石
Bluebright=ブルーブライト
Bluebright Vine=ブルーブライトのツタ
Bound Leather=綴じ革
Brimwood=ブリムウッド
Brown Bear Hide=ヒグマの毛皮
Canopy=林冠
Carnelian=カーネリアン
Cave Chitin=洞窟のキチン
Cerulean Vines=セルリアンのツタ
Chalk=チョーク
Charoite=チャロアイト
Chlorophyte=クロロファイト
Chorundum=コランダム
Chromite=クロム鉄鉱
Cincinnasite=シンシナサイト
Cincinnasite Diamond=シンシナサイトダイヤモンド
Citrine=シトリン
Cobalt Obsidian=コバルト黒曜石
Coprolith=糞石
Crystal Shard=結晶の欠片
Crystalline=結晶の
Crystallized Ichor=結晶化したイコル
Cypress=イトスギ
Darkstone=ダークストーン
Dawnstone=ドーンストーン
Deadwood=枯れ木
Demonite=デモナイト
Dense Vine=密なツタ
Diopside=透輝石
Dolerite=粗粒玄武岩
Draco Arcanus=ドラコ・アルカヌス
Dragon Scale=竜の鱗
Dragon Tree=竜血樹
Dropleaf=ドロップリーフ
Dryophyllum=ドリオフィラム
Dusk=夕闇
Dusk Vine=夕闇のツタ
Echoing=残響の
Edelwood=エーデルウッド
Ember Crystal Cluster=燃えさしの結晶の塊
End Lotus=エンドロータス
Enderite=エンデライト
Endium=エンディウム
Eternal Crystal=永遠の結晶
Eternal Flavolite=永遠のフラボライト
Eternium=エターニウム
Eternium Nugget=エターニウムの塊
Eucalyptus=ユーカリ
Eudialyte=ユーディアライト
Eudialyte Gem=ユーディアライトの宝石
Fiery=炎の
Fine Silk=上質な絹
Fir=モミ
Fire Amber=炎の琥珀
Fire Dragonsteel=炎の竜鋼
Fireruby=炎のルビー
Flavolite=フラボライト
Flaxen=亜麻色の
Flood Basalt=洪水玄武岩
Flowered=花咲く
Fluorite Crystal=蛍石の結晶
Foxii=フォクシー
Frostbright=フロストブライト
Frostbright Vine=フロストブライトのツタ
Frozen Quartz=凍ったクォーツ
Fungyss=ファンギス
Ginkgo=イチョウ
Glacian=グラシアン
Glacium=グラシウム
Glinted Allurite Cluster=輝くアルライトの塊
Glinted Amethyst Cluster=輝くアメジストの塊
Glinted Lumiere Cluster=輝くルミエールの塊
Glistering=きらめく
Glistering Ivy=きらめくツタ
Glowood=グローウッド
Golden Dragon Scale=金の竜の鱗
Golden Vine=金のツタ
Granodiorite=花崗閃緑岩
Green Bioshroom=緑色のバイオシュルーム
Grey Limestone=灰色の石灰岩
Grim=陰鬱な
Grimwood=グリムウッド
Guanostone=グアノストーン
Heavy Bone=重い骨
Heliodor=ヘリオドール
Helix=ヘリックス
Hellbark=ヘルバーク
Hellwood=ヘルウッド
Hoaky=ホーキー
Horizonite=ホライゾナイト
Ice Dragonsteel=氷の竜鋼
Iguana Leather=イグアナの革
Iolite=アイオライト
Iridite=イリダイト
Jacaranda=ジャカランダ
Jade=翡翠
Jellyshroom=ゼリーキノコ
Joshua=ジョシュア
Jungle Vine=ジャングルのツタ
Kapok=カポック
Kapok Vine=カポックのツタ
Kousa=ヤマボウシ
Kuko=クコ
Kyanite=カイヤナイト
Lacugrove=ラクグローブ
Larch=カラマツ
Laurel=ゲッケイジュ
Lightning Dragonsteel=雷の竜鋼
Linium=リニウム
Lucernia=ルセルニア
Lumiere Shard=ルミエールの欠片
Lunar Vine=月のツタ
Magnolia=モクレン
Mahogany=マホガニー
Majungasaurus Scute=マジュンガサウルスの鱗板
Malachite=マラカイト
Mangrove=マングローブ
Maple=カエデ
Maple Vine=カエデのツタ
Mauve=モーブ
Moldavite=モルダバイト
Morado=モラド
Mossy Glowshroom=苔むしたヒカリタケ
Mushroom Fir=キノコモミ
Neon Equisetum=ネオンスギナ
Neridium=ネリジウム
Nether Mushroom=ネザーキノコ
Nether Reed=ネザーアシ
Nether Ruby=ネザールビー
Nether Sakura=ネザーサクラ
Netherite Opal=ネザライトオパール
Netherwood=ネザーウッド
Occult Gem=オカルトの宝石
Olivine=カンラン石
Onyx=オニキス
Opal=オパール
Opal Chunk=オパールの塊
Palerock=ペールロック
Palm=ヤシ
Passion Vine=パッションのツタ
Penumbra Wood=半影の木
Penumbral=半影の
Penumbral Vine=半影のツタ
Peridotite=カンラン岩
Petrified Wood=珪化木
Pewen=ペウェン
Phyllite=千枚岩
Pine=マツ
Pink Bioshroom=桃色のバイオシュルーム
Plasma=プラズマ
Poise=ポイズ
Polar Bear Hide=シロクマの毛皮
Poseidite=ポセイダイト
Poseidite Nugget=ポセイダイトの塊
Pream=プリーム
Prehistoric Ginkgo=先史時代のイチョウ
Primordial=原初の
Primordial Wood=原初の木
Prismarite Cluster=プリズマライトの塊
Purified Titanite Shard=精製チタナイトの欠片
Pyridium=ピリジウム
Pyrope=パイロープ
Pythadendron=ピタデンドロン
Quartz Steel=クォーツ鋼
Quartzite=珪岩
Radioactive=放射性の
Radrock=ラッドロック
Reaching Vine=伸びるツタ
Redwood=セコイア
Reinforced Deorum=強化デオルム
Rex Tooth=レックスの歯
Rhyolite=流紋岩
Riftite Shard=リフタイトの欠片
Riverwood=リバーウッド
Rocky=岩の
Rosewood=ローズウッド
Rubeus=ルベウス
Samurai Steel=侍鋼
Sandy Jadestone=砂色の翡翠石
Sapphire Shard=サファイアの欠片
Scarlet Emerald=緋色のエメラルド
Schist=片岩
Sculk Vine=スカルクのツタ
Sculkium=スカルキウム
Sculkium Nugget=スカルキウムの塊
Serpentbone=蛇骨
Shulkerate=シュルケレート
Shulkerate Nugget=シュルケレートの塊
Silk=絹
Silken=絹の
Silver Dragon Scale=銀の竜の鱗
Silverbell=アメリカアサガラ
Slate=粘板岩
Smaragdant=スマラグダント
Snakeskin=蛇革
Socotra=ソコトラ
Spire Stone=尖塔の石
Stalagnate=スタラグネート
Starlit Vine=星明かりのツタ
Strophar=ストロファー
Sulfuric=硫黄の
Sulfuric Rock=硫黄の岩
Tanned Leather=なめし革
Tanzanite=タンザナイト
Tenanea=テナネア
Tenanea Flowers=テナネアの花
Terminite=ターミナイト
Thallasium=タラシウム
Thorned=とげのある
Thornwood=ソーンウッド
Thunder Vine=雷のツタ
Tigerwood=タイガーウッド
Titanite=チタナイト
Topaz=トパーズ
Topaz Shard=トパーズの欠片
opaz Shard=トパーズの欠片
Totemic Gold=トーテムの金
Totemic Gold Nugget=トーテムの金塊
Tough=頑丈な
Tough Hide=頑丈な皮
Towerwood=タワーウッド
Trike Horn=トリケラの角
Trio=トリオ
Trumpet=トランペット
Turquoise=ターコイズ
Twilight Oak=トワイライトオーク
Twisted Vine=ねじれたツタ
Twisted Wood=ねじれた木
Umbral=影の
Umbralith=アンブラリス
Umbran=アンブラン
Umbrella Tree=アンブレラツリー
Unbreakability Seal=不壊の封印
Venomite=ヴェノマイト
Violecite=ヴィオレサイト
Violite=ヴィオライト
Violium=ヴィオリウム
Virid Jadestone=緑の翡翠石
Void Chitin=虚無のキチン
Void Crystal=虚無の結晶
Void Crystal Shard=虚無の結晶の欠片
Void Shale=虚無の頁岩
Voidic Crystal=虚無の結晶
Wartwood=ウォートウッド
Whalebone=鯨骨
White Diamond=白ダイヤモンド
White Granite=白花崗岩
White Opal=ホワイトオパール
Willow=ヤナギ
Wisteria=フジ
Wither Rod=ウィザーの棒
Yellow Bioshroom=黄色のバイオシュルーム
Zircon=ジルコン
Zircon Gem=ジルコンの宝石
Zirconium Gem=ジルコニウムの宝石
Calorite=カロライト
Desh=デッシュ
Glacio Stone=グラシオの石
Mars Stone=火星の石
Mercury Stone=水星の石
Moon Stone=月の石
Ostrum=オストラム
Sky Stone=スカイストーン
Steel=鋼鉄
Venus Stone=金星の石
Galena=方鉛鉱
Limestone=石灰岩
Pearl=真珠
Uranium=ウラン
Crocodile Scute=ワニの鱗板
Elastic Tendon=伸縮性の腱
Tendon=腱
Froststalker Horn=フロストストーカーの角
Gazelle Horn=ガゼルの角
Kangaroo Hide=カンガルーの皮
Rocky Shell=岩の殻
Spiked Scute=とげのある鱗板
Spiky=とげとげの
Straddlite=ストラドライト
Abyssal Amethyst=深淵のアメジスト
Echo of the Ship Graveyard=船の墓場の残響
Yucca=ユッカ
Draconic=竜の
Anchor=アンカー
Blooming=花咲く
Neon=ネオン
Magic Wood=魔法の木
Willow Vine=ヤナギのツタ
Aquite=アクアイト
Bluebright Wood=ブルーブライトの木
Brumble Vine=ブランブルのツタ
Cinderstone=シンダーストーン
Comet=彗星
Comet Wood=彗星の木
Dusk Wood=夕闇の木
Frostbright Wood=フロストブライトの木
Lunar Stone=月の石
Lunar Wood=月の木
Maple Wood=カエデの木
Moonstone=ムーンストーン
Rimestone=ライムストーン
Starlit Wood=星明かりの木
Taratite=タラタイト
Turquoise Stone=ターコイズの石
Umber=アンバー
Sunstone Crystal=サンストーンの結晶
Andesite Alloy=安山岩合金
Asurine=アズリン
Brass=真鍮
Crimsite=クリムサイト
Ochrum=オクルム
Refined Radiance=精製された輝き
Scorchia=スコーチア
Scoria=スコリア
Shadow Steel=影鋼
Veridium=ヴェリジウム
Zinc=亜鉛
Sculk Bone=スカルクの骨
Echo Wood=残響の木
Gloomslate=グルームスレート
Sculk Stone=スカルクの石
Warden=ウォーデン
Reinforced Echo Shard=強化された残響の欠片
Soul Crystal=魂の結晶
Azalea=ツツジ
Coconut=ココナッツ
Flowering Azalea=花の咲いたツツジ
Walnut=クルミ
Lead=鉛
Silver=銀
Twisted=ねじれた
Cerulean=セルリアン
Indigo=インディゴ
Plum=プラム
Ruby=ルビー
Enderium=エンダリウム
Blaze=ブレイズ
Bronze=青銅
Cobalt=コバルト
Hellfire=地獄の炎
Marble=大理石
Mithril=ミスリル
Obsidian=黒曜石
Platinum=白金
Quartz=クォーツ
Redstone=レッドストーン
Sapphire=サファイア
Tin=スズ
Titanium=チタン
Tungsten=タングステン
Wither=ウィザー
Rose Quartz=ローズクォーツ
Azure=紺碧
Ashen Wood=灰色の木
Jasper=ジャスパー
Myalite=マイアライト
Shale=頁岩
Trumpet Wood=トランペットの木
Azure Electrum=アズールエレクトラム
Azure Silver=アズールシルバー
Blaze Gold=ブレイズゴールド
Crimson Iron=クリムゾンアイアン
Crimson Steel=クリムゾンスチール
Flax=亜麻
Fluffy String=ふわふわの糸
Sinew=筋
Tyrian Steel=ティリアンスチール
Azure Electrum Nugget=アズールエレクトラムの塊
Blaze Gold Nugget=ブレイズゴールドの塊
Crimson Iron Nugget=クリムゾンアイアンの塊
Crimson Steel Nugget=クリムゾンスチールの塊
Tyrian Steel Nugget=ティリアンスチールの塊
Peridot=ペリドット
Bamboo=竹
Zirconium=ジルコニウム
Darkwood=ダークウッド
Dark=暗い
Fiery Metal=炎の金属
Ironwood=アイアンウッド
Knightmetal=ナイトメタル
Knightly=騎士の
Naga Scale=ナーガの鱗
Steeleaf=スチールリーフ
Gabbro=斑れい岩
Petrified=石化した
Driftwood=流木
Ichor=イコル
Thunder=雷
""".strip().splitlines())
m = json.loads((WORK / "extracted/tetranomicon.json").read_text(encoding="utf-8"))["missing"]
CODE = re.compile(r"^((?:§.)*)(.*?)((?:§.)*)$")
out, left = {}, []
for k, v in m.items():
    if not k.startswith("tetra.material."):
        continue
    sock = v.endswith(" socket")
    base = v[:-7] if sock else v
    c = CODE.match(base)
    name = c.group(2)
    if name == "Trio" and "§q" in base:  # §cT§qr§9io§r のような1文字ずつの色付けはそのまま
        out[k] = v
        continue
    if name not in D:
        left.append(v)
        continue
    j = c.group(1) + D[name] + c.group(3)
    out[k] = j + "のソケット" if sock else j
(WORK / "tr/batch_18_tetranomicon_gen.json").write_text(json.dumps({"tetranomicon": out}, ensure_ascii=False, indent=1), encoding="utf-8")
print(len(out), "未対応:", left)
